# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"

# Formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Functions
fn_params_layout = "Tall"

# Structs and Enums
struct_lit_width = 0

# Misc
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true

